server:
  port: 9090

spring:
  cloud:
    gateway:
      routes:
        - id: public-server-api # 이름
          uri: http://localhost:8080 # api 서버 주소
          predicates:
            # 게이트 웨이로 들어오는 주소 중에서 /service-api/open-api/로 시작하는 주소를 찾아서 api 서버로 보내겠다
            - Path=/service-api/open-api/**
          filters:
            # service-api에 해당되는 부분을 날려버리고 나저미 주소만 api 서버 주소에 붙어서 날아가는 정규식
            - RewritePath=/service-api(?<segment>/?.*), $\{segment}
            # Component로 등록된 Kotlin class와 동일한 이름
            - ServiceApiPrivateFilter
            - ServiceApiPublicFilter